apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: production
  labels:
    app: auth-service
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
        environment: production
    spec:
      serviceAccountName: smartgrid-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      containers:
        - name: auth-service
          image: 169720629031.dkr.ecr.ap-south-1.amazonaws.com/smartgrid-default-auth-service:latest
          ports:
            - containerPort: 3001
          envFrom:
            - configMapRef:
                name: smartgrid-config
            - secretRef:
                name: smartgrid-secrets
          env:
            - name: PORT
              value: "3001"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 3001
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ready
              port: 3001
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
