apiVersion: v1
kind: Service
metadata:
  name: billing-service
  namespace: production
  labels:
    app: billing-service
    environment: production
spec:
  selector:
    app: billing-service
  ports:
    - name: http
      port: 3004
      targetPort: 3004
      protocol: TCP
  type: ClusterIP
