apiVersion: v1
kind: Secret
metadata:
  name: smartgrid-secrets
  labels:
    app.kubernetes.io/name: smartgrid
type: Opaque
data:
  DB_PASSWORD: {{ .Values.database.password | b64enc | quote }}
  JWT_SECRET: {{ .Values.jwtSecret | b64enc | quote }}
