{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartgrid-sa
  annotations:
    {{- toYaml .Values.serviceAccount.annotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: smartgrid
{{- end -}}
