{{- range $serviceName, $service := .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    app: {{ $serviceName }}
spec:
  type: ClusterIP
  ports:
    - port: {{ $service.port }}
      targetPort: {{ $service.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ $serviceName }}
---
{{- end }}
