apiVersion: v1
kind: ConfigMap
metadata:
  name: smartgrid-config
  namespace: production
  labels:
    app.kubernetes.io/name: smartgrid
    environment: production
data:
  NODE_ENV: "production"
  DB_PORT: "3306"
  DB_NAME: "smartgrid"
  DB_USER: "smartgrid_user"
  AWS_REGION: "ap-south-1"
  BEDROCK_REGION: "us-east-1"
  BEDROCK_MODEL_PRIMARY: "us.amazon.nova-pro-v1:0"
  BEDROCK_MODEL_FALLBACK: "us.amazon.nova-lite-v1:0"
  CONSUMER_SERVICE_URL: "http://consumer-service:3002"
  BILLING_SERVICE_URL: "http://billing-service:3004"
  METER_SERVICE_URL: "http://meter-service:3003"
