apiVersion: v1
kind: ServiceAccount
metadata:
  name: smartgrid-sa
  namespace: production
  labels:
    app.kubernetes.io/name: smartgrid
    environment: production
  annotations:
    # IRSA: allows pods to assume the EKS pod IAM role via OIDC — no static credentials needed
    eks.amazonaws.com/role-arn: arn:aws:iam::169720629021:role/smartgrid-default-eks-pod-role
