apiVersion: v1
kind: Service
metadata:
  name: meter-service
  namespace: production
  labels:
    app: meter-service
    environment: production
spec:
  selector:
    app: meter-service
  ports:
    - name: http
      port: 3003
      targetPort: 3003
      protocol: TCP
  type: ClusterIP
