name: CI — auth-service

on:
  workflow_call:

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service:      auth-service
      port:         3001
      healthz_path: /healthz
    secrets: inherit
