name: CI — consumer-service

on:
  workflow_call:

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service:      consumer-service
      port:         3002
      healthz_path: /healthz
    secrets: inherit
